import { Roboto } from "next/font/google";
import { Poppins } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
// import { updateCart } from "@/action";
// import { updateCart } from "@/action";

const roboto = Roboto({
  weight: ['400', "500", '700'],
  subsets: ['latin'],
  display: 'swap',
})
const poppins = Poppins({
  weight: ['400', "500", "600", '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "LWS-Cart",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // await updateCart()
  return (
    <html lang="en">
      <head>
        {/* <link rel="stylesheet" href="../node_modules/@fortawesome/fontawesome-free/css/all.min.css" /> */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body className={poppins.className}>
        <Header />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
